[package]
name = "jamjar"
version = "0.2.0"
authors = ["***Realname*** ***Lastname*** <***redacted.email@redacted.nope***>"]
description = "A collection of useful crates and utilities for quickly bootstrapping games for game jams."
edition = "2018"

[features]
default = []
codegen = ["edres"]
reloading = ["dirty_static", "dymod", "lazy_static", "resource", "serde_yaml", "toml"]
windowing = ["winit"]
everything = ["reloading", "windowing"]

[dependencies]
dirty_static = { version = "~0.1.1", optional = true }
edres = { version = "~0.5", optional = true, features = ["experimental-files-enum", "toml-parsing", "yaml-parsing"] }
lazy_static = { version = "~1.4.0", optional = true }
resource = { version = "~0.5", optional = true }
serde = { version = "~1.0.117", features = ["derive"] }
serde_yaml = { version = "~0.8.14", optional = true }
toml = { version = "~0.5.7", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
dymod = { git = "https://github.com/mistodon/dymod", branch = "web", optional = true, default-features = false, features = ["force-static"] }
winit = { version = "~0.23", optional = true, features = ["web-sys"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dymod = { git = "https://github.com/mistodon/dymod", branch = "web", optional = true }
winit = { version = "~0.23", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.6"
features = [ "console", "Document", "Element", "HtmlElement", "Node", "Window" ]
