[package]
name = "jamjar"
version = "0.2.0"
authors = ["***Realname*** ***Lastname*** <***redacted.email@redacted.nope***>"]
description = "A collection of useful crates and utilities for quickly bootstrapping games for game jams."
edition = "2018"

[features]
default = []
codegen = ["edres"]
windowing = ["winit"]
everything = ["windowing"]

[dependencies]
edres = { version = "~0.5", optional = true, features = ["experimental-files-enum", "toml-parsing", "yaml-parsing"] }
serde = { version = "*", features = ["derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies.winit]
version = "~0.23"
optional = true
features = ["web-sys"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.winit]
version = "~0.23"
optional = true

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.6"
features = [ "console", "Document", "Element", "HtmlElement", "Node", "Window" ]
