[package]
name = "jamjar"
version = "0.2.0"
authors = ["***Realname*** ***Lastname*** <***redacted.email@redacted.nope***>"]
description = "A collection of useful crates and utilities for quickly bootstrapping games for game jams."
edition = "2018"

[features]
default = ["everything"]
audio = ["rodio"]
codegen = ["edres"]
drawsloth = ["gfx", "windowing"]
drawgroovy = ["gfx", "windowing"]
gfx = ["gfx-hal", "gfx-auxil", "image"]
reloading = ["dirty_static", "dymod", "lazy_static", "resource", "serde_yaml", "toml"]
resources = ["resource"]
timing = ["wasm-bindgen"]
windowing = ["winit"]
everything = ["audio", "reloading", "resources", "timing", "windowing"]

opengl = ["gfx-backend-gl"]
metal = ["gfx-backend-metal"]

[dependencies]
dirty_static = { version = "~0.1.1", optional = true }
edres = { version = "~0.5", optional = true, features = ["experimental-files-enum", "toml-parsing", "yaml-parsing"] }
gfx-hal = { path = "../gfx/src/hal", optional = true }
gfx-backend-gl = { path = "../gfx/src/backend/gl", optional = true }
gfx-backend-metal = { path = "../gfx/src/backend/metal", optional = true }
image = { version = "~0.23.12", optional = true }
lazy_static = { version = "~1.4.0", optional = true }
resource = { version = "~0.5", optional = true, features = ["experimental-resource-list"] }
rodio = { version = "~0.13.0", optional = true, features = ["flac", "vorbis", "wav"], default-features = false }
serde = { version = "~1.0.117", features = ["derive"] }
serde_yaml = { version = "~0.8.14", optional = true }
toml = { version = "~0.5.7", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
cpal = { version = "0.13.1", features = ["wasm-bindgen"] }
dymod = { git = "https://github.com/mistodon/dymod", branch = "web", optional = true, default-features = false, features = ["force-static"] }
gfx-auxil = { path = "../gfx/src/auxil/auxil", optional = true }
wasm-bindgen = { version = "~0.2.69", optional = true }
winit = { version = "~0.23", optional = true, features = ["web-sys"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dymod = { git = "https://github.com/mistodon/dymod", branch = "web", optional = true }
winit = { version = "~0.23", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.6"
features = [ "console", "Document", "Element", "HtmlElement", "Node", "Window" ]
