[package]
name = "jamjar"
version = "0.2.0"
authors = ["Vi <violet@hey.com>"]
description = "A collection of useful crates and utilities for quickly bootstrapping games for game jams."
edition = "2018"

[features]
default = ["everything"]
audio = ["rodio"]
codegen = ["edres"]
drawsloth = ["gfx", "windowing"]
drawgroovy = ["gfx", "windowing"]
gfx = ["gfx-hal", "gfx-auxil", "image"]
input = ["buttons", "windowing"]
math = ["okmath"]
reloading = ["dirty_static", "dymod", "lazy_static", "resource", "serde_yaml", "toml"]
resources = ["resource"]
timing = ["wasm-bindgen"]
windowing = ["winit"]
everything = ["audio", "input", "math", "reloading", "resources", "timing", "windowing"]

opengl = ["gfx-backend-gl"]
metal = ["gfx-backend-metal"]
bypass_spirv_cross = []

[dependencies]
buttons = { version = "~0.3.1", features = ["winit-support"], optional = true }
edres = { version = "~0.5", optional = true, features = ["experimental-files-enum", "toml-parsing", "yaml-parsing"] }
gfx-hal = { path = "../../forks/gfx/src/hal", branch = "mistodon", optional = true }
gfx-backend-gl = { path = "../../forks/gfx/src/backend/gl", branch = "mistodon", optional = true }
gfx-backend-metal = { path = "../../forks/gfx/src/backend/metal", branch = "mistodon", optional = true }
image = { version = "~0.23.14", optional = true }
lazy_static = { version = "~1.4.0", optional = true }
log = "~0.4.14"
okmath = { path = "../okmath", optional = true }
serde = { version = "~1.0.125", features = ["derive"] }
serde_yaml = { version = "~0.8.17", optional = true }
toml = { version = "~0.5.7", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = "~0.2.0"
dirty_static = { version = "~0.1.1", features = ["force-static"], optional = true }
dymod = { version = "~0.3", optional = true, default-features = false, features = ["force-static"] }
gfx-auxil = { path = "../../forks/gfx/src/auxil/auxil", branch = "mistodon", optional = true }
resource = { version = "~0.5", optional = true, features = ["experimental-resource-list", "force-static"] }
rodio = { version = "~0.13.1", optional = true, features = ["flac", "vorbis", "wav", "wasm-bindgen"], default-features = false }
wasm-bindgen = { version = "~0.2.73", optional = true }
winit = { version = "~0.24", optional = true, features = ["web-sys"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dirty_static = { version = "~0.1.1", optional = true }
dymod = { version = "~0.3", optional = true }
resource = { version = "~0.5", optional = true, features = ["experimental-resource-list"] }
rodio = { version = "~0.13.1", optional = true, features = ["flac", "vorbis", "wav"], default-features = false }
winit = { version = "~0.24", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.50"
features = [ "console", "Document", "Element", "HtmlElement", "Node", "Window" ]
