#!/usr/bin/env bash

set -eu
set -o pipefail

cargo check
cargo check --no-default-features
cargo check --features wdev
cargo check --features wdev
cargo test --features wdev

(cd jamjar_examples && cargo check)
