#!/usr/bin/env bash

set -eu
set -o pipefail

cargo check
cargo check --no-default-features
cargo check --features metaldev
cargo check --features metaldev
cargo test --features metaldev

(cd jamjar_examples && cargo check)
