#!/usr/bin/env bash

set -eu
set -o pipefail

readonly host=${2:-}

(cd jamjar_examples && jamjar web -b $1 --features opengl)

if [[ "$host" == "-h" ]]; then
    (cd jamjar_examples && http target/jamjar_web)
fi
